[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
counter = "EvDoy5PvRxvE5i9TJzj63Hmf5toV9xUZARREcQjzZY9X"

[programs.devnet]
counter = "EvDoy5PvRxvE5i9TJzj63Hmf5toV9xUZARREcQjzZY9X"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
